num_layers: 4
target_vocab_size: 16000
d_model: 128
dff: 512
num_heads: 8
dropout_rate: 0.1
storage_path: null
max_length: 40
epochs: 50
batch_size: 64
# save a checkpoint every x epochs
checkpoint: 5
max_checkpoint: 10
# select a custom checkpoint to start with
# (else it will automatically select the latest checkpoint)
custom_checkpoint: null

# train/eval/test/deploy
mode: "test"
eval_limit: 10
exit_phrase: ".exit"